#!/bin/bash

xa -l toc -o ./vic/p5ed.bin ./src/p5ed.asm
#printf "\x00\x60" | cat - ./vic/p5ed.bin > ./vic/p5ed
printf "\x00\xa0" | cat - ./vic/p5ed.bin > ./vic/p5ed
cat ./vic/p5ed.bin ./src/padding.bin | head -c 8192 > ./vic/p5ed.eep
cp ./vic/p5ed ~/personal/vic


